// <auto-generated />

using System.Reflection;

[assembly: AssemblyCopyright("Copyright 2014 Craig Wilson")]
[assembly: AssemblyVersion("0.1.0.0")]
[assembly: AssemblyInformationalVersion("0.1.0")]
[assembly: AssemblyFileVersion("0.1.0.0")]
[assembly: AssemblyConfiguration("Release")]
